# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringdb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estringdb.proto\x12\x08stringdb\"\x1e\n\x0fGetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\rGetValueReply\x12\r\n\x05value\x18\x01 \x01(\t\"-\n\x0fSetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\rSetValueReply\x12\r\n\x05value\x18\x01 \x01(\t\" \n\x11\x43ountValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x0f\x43ountValueReply\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\xd6\x01\n\x08StringDb\x12@\n\x08GetValue\x12\x19.stringdb.GetValueRequest\x1a\x17.stringdb.GetValueReply\"\x00\x12@\n\x08SetValue\x12\x19.stringdb.SetValueRequest\x1a\x17.stringdb.SetValueReply\"\x00\x12\x46\n\nCountValue\x12\x1b.stringdb.CountValueRequest\x1a\x19.stringdb.CountValueReply\"\x00\x42\x1fZ\x1dgrpc-stringdb-sample/stringdbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stringdb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035grpc-stringdb-sample/stringdb'
  _GETVALUEREQUEST._serialized_start=28
  _GETVALUEREQUEST._serialized_end=58
  _GETVALUEREPLY._serialized_start=60
  _GETVALUEREPLY._serialized_end=90
  _SETVALUEREQUEST._serialized_start=92
  _SETVALUEREQUEST._serialized_end=137
  _SETVALUEREPLY._serialized_start=139
  _SETVALUEREPLY._serialized_end=169
  _COUNTVALUEREQUEST._serialized_start=171
  _COUNTVALUEREQUEST._serialized_end=203
  _COUNTVALUEREPLY._serialized_start=205
  _COUNTVALUEREPLY._serialized_end=237
  _STRINGDB._serialized_start=240
  _STRINGDB._serialized_end=454
# @@protoc_insertion_point(module_scope)
